apiVersion: apps/v1
kind: Deployment
metadata:
  name: libro-microservice-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: libros
  template:
    metadata:
      labels:
        app: libros
    spec:
      containers:
      - name: libros
        image: libromicroservice.azurecr.io/amiltonr/libromicroservice
        imagePullPolicy: Always
        ports:
        - containerPort: 80
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  name: libro-microservice-svc
spec:
  selector:
    app: libros
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
